version: '3.7'
services:
  admindb:
    image: mysql:latest
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=BatchProcessor
      - MYSQL_MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    command: [ '--default-authentication-plugin=mysql_native_password' ]
    volumes:
      - admin-db:/var/lib/mysql
    ports:
      - "3307:3306"

  admin:
    image: pyordan/batch_admin:1.2
    depends_on:
      - admindb
      - rabbitMQ
    environment:
      DB_URL: jdbc:mysql://admindb:3307/BatchProcessor
      SERVER_PORT: 9001
      DB_USERNAME: root
      DB_PASSWORD: root
      RABBIT_HOST: rabbitMQ
      RABBIT_QUEUE: batch_job
    ports:
      - "9001:9001"

  batchDb:
    image: mysql:latest
    platform: linux/amd64
    command: [ '--default-authentication-plugin=mysql_native_password' ]
    environment:
    - MYSQL_DATABASE=batch_demo_db
    - MYSQL_MYSQL_ROOT_USER=root
    - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3308:3306"
    volumes:
      - batch-db:/var/lib/mysql

  rabbitMQ:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"


  batch_processor:
    image: pyordan/batch_processor:1.2
    depends_on:
      - batchDb
      - rabbitMQ
    environment:
      DB_URL: jdbc:mysql://batchDb:3308/batch_demo_db
      SERVER_PORT: 8001
      DB_USERNAME: root
      DB_PASSWORD: root
      RABBIT_HOST: rabbitMQ
      RABBIT_QUEUE: batch_job
    ports:
      - "8001:8001"

volumes:
  admin-db:
  batch-db:


