server:
  port: 9004
spring:
  config:
    import: development.yml
  datasource:
    url: jdbc:mysql://localhost:3306/BatchProcessor
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

  rabbitmq:
    host: localhost
    queue: batch_job

jwt:
  expiry:
  secret:
